name: telefonos_hospital_flutter
description: Directorio telefónico para el Hospital Materno Infantil e Insular

# Evitar publicación en pub.dev
publish_to: 'none'

# Versión de la aplicación
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^5.0.1
  path_provider: ^2.0.11
  http: ^0.13.5
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Configuración de Flutter
flutter:
  uses-material-design: true
  
  # Incluir archivos de assets
  assets:
    - assets/
    - assets/MATERNO-2025.csv
    - MATERNO-2025.csv