name: telefonos_hospital_flutter
description: Directorio telefónico para el Hospital Materno Infantil e Insular

# Evitar publicación en pub.dev
publish_to: 'none'

# Versión de la aplicación
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  csv: ^6.0.0
  path_provider: ^2.1.5
  http: ^1.3.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Cambiado de ^5.0.0 a ^2.0.0 para compatibilidad con Dart 3.0.0

# Configuración de Flutter
flutter:
  uses-material-design: true
  
  # Incluir archivos de assets
  assets:
    - assets/
    - assets/MATERNO-2025.csv
    - MATERNO-2025.csv