name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Establece permisos para el token GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build web
        run: flutter build web --base-href /Telefonos/
        
      - name: Prepare web assets
        run: |
          # Verificar la estructura de directorios
          ls -la build/web/
          
          # Asegurar que el manifest.json esté en la carpeta correcta
          cp -f web/manifest.json build/web/
          
          # Verificar que flutter_bootstrap.js existe
          if [ ! -f "build/web/flutter_bootstrap.js" ]; then
            echo "// Bootstrap script for Flutter web" > build/web/flutter_bootstrap.js
          fi
          
          # Copiar el CSV
          cp -f MATERNO-2025.csv build/web/
          mkdir -p build/web/assets
          cp -f assets/MATERNO-2025.csv build/web/assets/ || true
          
          # Crear archivo .nojekyll
          touch build/web/.nojekyll
          
          # Listar archivos para verificar
          echo "Contenido de build/web:"
          ls -la build/web/
          
          # Crear archivo .nojekyll para evitar procesamiento Jekyll
          touch build/web/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true