name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Establece permisos para el token GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build web
        run: flutter build web --base-href /Telefonos/
        
      - name: Prepare web assets
        run: |
          # Asegurar que el CSV esté disponible en la carpeta web
          cp -f MATERNO-2025.csv build/web/ || true
          cp -f assets/MATERNO-2025.csv build/web/assets/ || true
          
          # Crear manifest.json si no existe
          if [ ! -f "build/web/manifest.json" ]; then
            echo '{
              "name": "Telefonos Hospital",
              "short_name": "Telefonos",
              "start_url": ".",
              "display": "standalone",
              "background_color": "#0175C2",
              "theme_color": "#0175C2",
              "description": "Directorio telefónico para el Hospital Materno Infantil e Insular",
              "orientation": "portrait-primary",
              "prefer_related_applications": false,
              "icons": [
                {
                  "src": "icons/Icon-192.png",
                  "sizes": "192x192",
                  "type": "image/png"
                },
                {
                  "src": "icons/Icon-512.png",
                  "sizes": "512x512",
                  "type": "image/png"
                }
              ]
            }' > build/web/manifest.json
          fi
          
          # Crear favicon.png si no existe
          if [ ! -f "build/web/favicon.png" ]; then
            # Copiar de web/favicon.png si existe
            cp -f web/favicon.png build/web/ || true
          fi
          
          # Crear archivo .nojekyll para evitar procesamiento Jekyll
          touch build/web/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true